language: ruby
rvm:
  - 2.2.1

env:
  - DB=sqlite

gemfile:
  - Gemfile

script:
#  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle install --jobs=3 --retry=3 --deployment
#  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rake
  - bundle exec rspec spec